### PR TITLE
harfbuzz 4.3.0

### PR DESCRIPTION
**Pull request by cbouss**
Home: https://harfbuzz.github.io/
Github: https://github.com/harfbuzz/harfbuzz/tree/4.3.0
License: https://github.com/harfbuzz/harfbuzz/blob/4.3.0/COPYING
Changelog: https://github.com/harfbuzz/harfbuzz/blob/4.3.0/NEWS (No removed API since current 3.1.2)
Jira: https://anaconda.atlassian.net/browse/DSNC-4886

Changes:
- Set version to 4.3.0
- Update about section
- Enable windows build
- Changes around pkg-config to correctly find dependencies
- Update build options as per 4.3.0

### CODE REVIEW

**Comment by cbouss** [comment]
TODO before merging:
- remove abs.yaml
- remove recipe/conda_build_config.yaml

**Review by varlackc — COMMENTED** [review]
This package looks good, we just have to make sure that we use the windows build from concourse for now.

**Review by skupr-anaconda — APPROVED** [review]
LGTM but we need more reviewers

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
